repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: no-commit-to-branch

  - repo: https://github.com/psf/black
    rev: "25.1.0"
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.9
    hooks:
      - id: ruff
        args: [ --fix ]
      #- id: ruff-format

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        exclude: "scripts/.*|.venv/.*|.*\\.bk|.*\\.example"

#  - repo: https://github.com/Yelp/detect-secrets
#    rev: v1.5.0
#    hooks:
#      - id: detect-secrets
#        args: [ "-C", ".secrets.baseline", "scan" ]
#        exclude: "scripts/.*|.venv/.*|.*\\.bk|.*\\.example"

#  - repo: https://github.com/ibm/detect-secrets
#    # This line indicates we will use the hook from ibm/detect-secrets to run scan during committing phase. - repo: https://github.com/ibm/detect-secrets
#    # If you desire to use a specific version of detect-secrets, you can replace `master` with other git revisions such as branch, tag or commit sha.
#    # You are encouraged to use static refs such as tags,instead of branch name
#    # Running "pre-commit autoupdate" would automatically updates rev to latest tag
#    rev: 0.13.1+ibm.61.dss
#    hooks:
#      - id: detect-secrets # pragma: whitelist secret
#      # Add options for detect-secrets-hook binary. You can run `detect-secrets-hook --help` to list out all possible options.
#      # You may also run `pre-commit run detect-secrets` to preview the scan result.
#      # when "--baseline" without "--use-all-plugins", pre-commit scan with just plugins in baseline file
#      # when "--baseline" with "--use-all-plugins", pre-commit scan with all available plugins
#        args: [ --baseline, .secrets.baseline, --use-all-plugins ]

  - repo: local
    hooks:
      - id: check-commit-signing
        name: Check Commit Signing
        entry: ./scripts/check_commit_signing.sh
        language: script