services:
  # Zookeeper service
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - am1_network

  # Kafka service
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.200.148:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - am1_network
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9092" ]  # Check if the Kafka port is available
      interval: 30s  # Run the check every 30 seconds
      retries: 3     # Retry up to 3 times if the health check fails
      timeout: 10s   # Timeout after 10 seconds
      start_period: 30s  # Allow Kafka 30 seconds to initialize before starting health checks

  # Backend service
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: am1_backend
    volumes:
      - ./backend/app:/app/app
      - ./backend/config:/app/config
      - ./backend/tests:/app/tests
#      - ./.certs:/etc/ssl/certs
      - ./.certs/server.crt:/etc/ssl/certs/pi-localhost.crt
      - ./.certs/server.key:/etc/ssl/certs/pi-localhost.key
    networks:
      - am1_network
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy  # Ensure Kafka is up before starting the backend service
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:user@am1_postgres_db:5432/am1
      - DEBUG=True
      - ENVIRONMENT=development
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
#      - SSL_CERT_FILE=/etc/ssl/certs/pi-localhost.crt
#      - SSL_KEY_FILE=/etc/ssl/certs/pi-localhost.key
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: am1_frontend
    volumes:
      - ./frontend/src:/app/src  # Only mount source code for hot reloading
      - ./frontend/public:/app/public
#      - ./.certs:/etc/ssl/certs
      - ./.certs/server.crt:/etc/ssl/certs/pi-localhost.crt
      - ./.certs/server.key:/etc/ssl/certs/pi-localhost.key
    networks:
      - am1_network
    ports:
      - "3000:3000"
    environment:
      #- VITE_API_URL=http://backend:8000
      - VITE_API_URL=https://backend:8000
      - NODE_ENV=development
      - VITE_DEV_SERVER_USE_HTTPS=true
      - NODE_EXTRA_CA_CERTS=/etc/ssl/certs/pi-localhost.crt
    depends_on:
      - backend

  # Database service
  postgres:
    image: postgres:17
    container_name: am1_postgres_db
    restart: always
    networks:
      - am1_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user
      POSTGRES_DB: am1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/app/db/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d am1"]
      interval: 10s
      retries: 5
      start_period: 20s

  kafka_consumer:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: kafka_consumer
    command: python /app/app/services/kafka/consumer_runner.py  # The script to run
    depends_on:
      - kafka  # Ensure Kafka is available before starting the consumer
    restart: always  # Restart the container if it fails
    networks:
      - am1_network

volumes:
  postgres_data:

networks:
  am1_network:
    driver: bridge
